config/routes.rb
Rails.application.routes.draw do
  # get 'loans/index'
  # get 'loans/new'
  # get 'loans/edit'
  # get 'loans/show'
  resources :loans

  root "loans#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/loan_details.rb
module LoanDetails
  def loan_details(loan_object)
    #(p x r x (1+r)**n)/((1+r)**(n-1))
    loan_hash = {}
    loan_hash['customer_name'] = loan_object.customer_name
    loan_hash['loan_amount'] = loan_object.loan_amount
    loan_hash['interest_rate'] = loan_object.rate_of_interest
    loan_hash['disbursement_date'] = loan_object.disbursement_date.strftime("%d/%m/%Y")
    loan_hash['payment_start_date'] = loan_object.disbursement_date.next_month.beginning_of_month.strftime("%d/%m/%Y")
    
    loans = []
    loan_release_date = loan_object.disbursement_date
    loan_emi_start_date = loan_release_date
    remaining_amount = loan_object.loan_amount.to_f
    term = loan_object.term.to_i
    interest = loan_object.rate_of_interest.to_f
    total_loan_interest = (loan_object.loan_amount.to_f * (interest / 100) * (1 + (interest / 100)) ** term) / ((1 + (interest / 100)) ** (term - 1)) / 2
    emi_amount = (loan_object.loan_amount.to_f + total_loan_interest.to_i) / term

    loan_object.term.times do
      loan_arr = []
      interest_amount = ((remaining_amount.to_f / term) / 100) * interest
      principal_amount = emi_amount - interest_amount
      loan_arr << loan_emi_start_date.next_month.beginning_of_month.strftime("%d/%m/%Y")
      loan_arr << remaining_amount.round(2)
      loan_arr << principal_amount.round(2)
      loan_arr << interest_amount.round(2)
      loan_arr << (principal_amount + interest_amount).round(2)
      rem_amount = (remaining_amount - principal_amount).round(2)
      rem_amount = 0.00 if rem_amount < 0
      loan_arr << rem_amount
      loans << loan_arr
      remaining_amount = (remaining_amount - principal_amount).round(2)
      loan_emi_start_date = loan_emi_start_date.next_month.beginning_of_month
    end
    loan_hash['loan_details'] = loans

    return loan_hash
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:edit, :update, :destroy]
  before_action :resources, only: [:index, :show]

  def index
  	@loans = resources
  end

  def new
  	@loan = Loan.new
  end

  def create
  	@loan = Loan.new(loan_params)
  	if @loan.save
  		flash[:notice] = "Customer data created successfully."
  	else
  		flash[:alert] = "Something went wrong!"
  	end
  	redirect_to loans_path
  end

  def edit
  end

  def update
  	if @loan.update(loan_params)
  		flash[:notice] = "Customer data updated successfully."
  	else
  		flash[:alert] = "Something went wrong!"
  	end
  		redirect_to loans_path
  end

  def show
  	@loan = resources
  end

  def destroy
    if @loan.destroy
    	flash[:notice] = "Customer data destroyed successfully."
    else
    	flash[:alert] = "Something went wrong!"
    end
  	redirect_to loans_path
  end

  private

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def resources
    LoanQuery.call(Loan.all, params)
  end

  def loan_params
  	params.require(:loan).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loans/_form.html.erb
<%= form_for @loan, :html => {id: "loan_id"} do |f| %>

  <div class="field">
    <%= f.label :customer_name %><br />
    <%= f.text_field :customer_name, autofocus: true, placeholder: "Customer Name" , :required => true%>
  </div>

  <div class="field">
    <%= f.label :loan_amount %><br />
    <%= f.number_field :loan_amount, autofocus: true, placeholder: "Loan Amount" , :required => true%>
  </div>
  
  <div class="field">
    <%= f.label :rate_of_interest %><br />
    <%= f.number_field :rate_of_interest, autofocus: true, placeholder: "Interest Rate" , :required => true, :min => 1, :max => 100 %>%
  </div>

  <div class="field">
    <%= f.label :disbursement_date %><br />
    <%= f.date_field :disbursement_date, :value => Date.today, autofocus: true, :required => true%>
  </div>

  <div class="field">
    <%= f.label :term %><br />
    <%= f.number_field :term, in: 12..50, step: 12, autofocus: true, placeholder: "Term" , :required => true%>
  </div>

    <%= f.hidden_field :created_by, :value => session[:current_user_id]%>
    <%= f.hidden_field :updated_by, :value => session[:current_user_id]%>

  <br>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
  
<% end %>

<script type="text/javascript">

  $(document).ready(function () {
    $("#loan_id").validate({
       debug: true,
       rules: {
        "loan[customer_name]": "required",
        }
    });
  });

</script>

app/views/loans/edit.html.erb
<h1>Edit Loan</h1>
<%= render 'form' %>
<br>
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Loan', new_loan_path %>
<% if @loans.present? %>
  <h1>Loans Details</h1>
  <table>
    <thead>
      <tr>
        <th>Customer Name</th>
        <th>Total Loan Amount</th>
        <th>Interest Rate</th>
        <th>Disbursement Date</th>
        <th>Terms</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @loans.each do |loan| %>
        <tr>
          <td><%= loan.customer_name %></td>
          <td><%= loan.loan_amount %></td>
          <td><%= loan.rate_of_interest %></td>
          <td><%= loan.disbursement_date.strftime("%d/%m/%Y") %></td>
          <td><%= loan.term %></td>
          <td><%= link_to 'EMI Details', loan %></td>
          <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
          <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>Please create loan for customers</h4>
<% end %>

<br>
<%= link_to 'Back', loans_path %>

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #dddddd;
  }
</style>

app/views/loans/new.html.erb
<h1>New Loan</h1>
<%= render 'form' %>
<br>
<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>
<% if @loan.present? %>
<h1>Monthly Loan Details</h1>
<div class="row">
  <div style="width:25%; float: left;">
  	<h4>Customer Name : <%= @loan['customer_name'] %></h4>
  	<h4>Loan Amount : <%= @loan['loan_amount'] %></h4>
  	<h4>Interest Rate : <%= @loan['interest_rate'] %>%</h4>
  	<h4>Disbursement Date : <%= @loan['disbursement_date'] %></h4>
    <h4>Payment Start Date : <%= @loan['payment_start_date'] %></h4>
  </div>
  <div style="width:75%; float: right;">
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Start Balance</th>
        <th>Principal</th>
        <th>Interest</th>
        <th>Total Amt</th>
        <th>End Balance</th>
      </tr>
    </thead>

    <tbody>
      <% @loan['loan_details'].each do |loan| %>
        <tr>
        	<% loan.each do |data| %>
            <td><%= data %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
<%end%>

<br>
<%= link_to 'Back', loans_path %>
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #dddddd;
  }
</style>